"""Response Guard — Phase 2 Milestone 9.

Rule-based grounding verifier that ensures generated answers are supported by
the evidence injected into the LLM prompt.  No LLM calls — pure token analysis.

Grounding check logic
---------------------
1. **No-info answer** — if the answer is the canonical "No information available"
   string (case-insensitive, normalized):
   - No evidence in context → PASS (correct refusal)
   - Evidence present → WARN ("over-refusal": LLM refused when evidence existed)

2. **Empty answer** — treated as an implicit refusal, same as (1).

3. **Normal answer** — compute *answer grounding score*:

   grounding_score = |answer_tokens ∩ evidence_tokens| / max(|answer_tokens|, 1)

   Where answer_tokens and evidence_tokens are stopword-filtered lowercase
   token sets.  This is a conservative lower bound — many valid answers
   use synonyms or rephrasings not literally present in the evidence, so
   this score is advisory rather than a hard gate.

4. **Conflict awareness** — if the context has conflicted entries and the
   answer does not contain an uncertainty marker
   ("uncertain", "unclear", "conflict", "contradiction", "both", "however",
   "but", "may", "might", "not sure", "not clear") → WARN.

5. **No evidence** + non-empty non-refusal answer → WARN (potential hallucination).

The guard never modifies the answer; it only annotates verdicts.
Callers decide whether to surface, log, or block based on ``passed``.
"""

from __future__ import annotations

import re
import string
from dataclasses import dataclass, field

from locomo_memory.phase2.context.builder import BuiltContext, _tokenize

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_NO_INFO_PATTERN = re.compile(
    r"no\s+information\s+available", re.IGNORECASE
)

_UNCERTAINTY_MARKERS: frozenset[str] = frozenset({
    "uncertain", "unclear", "conflict", "contradiction", "contradictory",
    "both", "however", "but", "may", "might", "not sure", "not clear",
    "conflicting", "disagree", "inconsistent",
})


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class GuardVerdict:
    """Result of one response-guard check."""

    passed: bool
    """True when the answer is acceptably grounded or a valid refusal."""

    grounding_score: float
    """Token-overlap fraction: answer_tokens ∩ evidence_tokens / answer_tokens.
    Range [0.0, 1.0].  Meaningless when ``is_no_info`` is True."""

    is_no_info: bool
    """True when the answer is the canonical refusal string."""

    answer_token_count: int
    evidence_token_count: int
    overlap_token_count: int

    warnings: list[str] = field(default_factory=list)
    """Advisory messages explaining any issues found."""

    @property
    def has_warnings(self) -> bool:
        return bool(self.warnings)


# ---------------------------------------------------------------------------
# ResponseGuard
# ---------------------------------------------------------------------------


class ResponseGuard:
    """Rule-based response grounding verifier.

    Args:
        min_grounding_score: if the grounding score drops below this threshold
            the verdict is marked as ``passed=False``.  Default 0.0 means the
            guard is purely advisory (never fails on score alone).
        require_uncertainty_for_conflicts: when True (default), answers for
            contexts with conflicting evidence must contain uncertainty markers
            or the verdict is marked as ``passed=False``.
    """

    def __init__(
        self,
        *,
        min_grounding_score: float = 0.0,
        require_uncertainty_for_conflicts: bool = True,
    ) -> None:
        self.min_grounding_score = min_grounding_score
        self.require_uncertainty_for_conflicts = require_uncertainty_for_conflicts

    # ------------------------------------------------------------------
    # Primary check
    # ------------------------------------------------------------------

    def check(self, answer: str, built_context: BuiltContext) -> GuardVerdict:
        """Verify that *answer* is grounded in *built_context*.

        Args:
            answer: the text generated by the answer LLM.
            built_context: the context built by :class:`~locomo_memory.phase2.context.builder.ContextBuilder`.

        Returns:
            :class:`GuardVerdict` with grounding score and any warnings.
        """
        warnings: list[str] = []
        answer_stripped = answer.strip()

        # ---- Detect canonical refusal -----------------------------------
        is_no_info = (
            not answer_stripped
            or bool(_NO_INFO_PATTERN.search(answer_stripped))
        )

        if is_no_info:
            if built_context.total_entries > 0:
                warnings.append(
                    "Answer is a refusal ('No information available') but "
                    f"{built_context.total_entries} evidence entries were provided. "
                    "Consider whether evidence was sufficient."
                )
                # Over-refusal is a warning, not a failure — the LLM may have
                # correctly judged the evidence irrelevant to this exact question.
            return GuardVerdict(
                passed=True,
                grounding_score=1.0,
                is_no_info=True,
                answer_token_count=0,
                evidence_token_count=len(built_context.evidence_tokens),
                overlap_token_count=0,
                warnings=warnings,
            )

        # ---- No evidence available, but non-refusal answer ---------------
        if built_context.total_entries == 0:
            warnings.append(
                "Answer is non-empty but no evidence was retrieved. "
                "This is a potential hallucination — no grounding exists."
            )
            return GuardVerdict(
                passed=False,
                grounding_score=0.0,
                is_no_info=False,
                answer_token_count=len(_tokenize(answer_stripped)),
                evidence_token_count=0,
                overlap_token_count=0,
                warnings=warnings,
            )

        # ---- Compute grounding score ------------------------------------
        answer_tokens = set(_tokenize(answer_stripped))
        evidence_tokens = built_context.evidence_tokens
        overlap = answer_tokens & evidence_tokens
        n_answer = len(answer_tokens)
        n_evidence = len(evidence_tokens)
        n_overlap = len(overlap)

        grounding_score = n_overlap / max(n_answer, 1)

        if grounding_score < self.min_grounding_score:
            warnings.append(
                f"Grounding score {grounding_score:.2f} is below the "
                f"minimum threshold {self.min_grounding_score:.2f}. "
                "The answer may not be supported by the retrieved evidence."
            )

        # ---- Conflict awareness check -----------------------------------
        if built_context.has_conflicted:
            answer_lower = answer_stripped.lower()
            has_uncertainty = any(
                marker in answer_lower for marker in _UNCERTAINTY_MARKERS
            )
            if not has_uncertainty and self.require_uncertainty_for_conflicts:
                warnings.append(
                    "Context contains conflicting memories but the answer "
                    "does not acknowledge uncertainty. Consider revising the "
                    "answer to note the conflict."
                )

        # ---- Determine pass/fail ----------------------------------------
        passed = grounding_score >= self.min_grounding_score

        return GuardVerdict(
            passed=passed,
            grounding_score=grounding_score,
            is_no_info=False,
            answer_token_count=n_answer,
            evidence_token_count=n_evidence,
            overlap_token_count=n_overlap,
            warnings=warnings,
        )

    # ------------------------------------------------------------------
    # Convenience batch check
    # ------------------------------------------------------------------

    def check_batch(
        self,
        answers: list[str],
        built_contexts: list[BuiltContext],
    ) -> list[GuardVerdict]:
        """Check a list of (answer, context) pairs. Returns one verdict per item."""
        if len(answers) != len(built_contexts):
            raise ValueError(
                f"answers and built_contexts must have the same length "
                f"({len(answers)} vs {len(built_contexts)})"
            )
        return [self.check(a, ctx) for a, ctx in zip(answers, built_contexts)]


# ---------------------------------------------------------------------------
# Re-exports
# ---------------------------------------------------------------------------

__all__ = ["GuardVerdict", "ResponseGuard"]
